# Generated by Django 5.0.1 on 2024-01-20 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pictureUrl',
            field=models.ImageField(default='image1.png', upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='productSize',
            field=models.CharField(default='m', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='quantityInStock',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
