# Generated by Django 5.0.1 on 2024-01-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_brand_product_pictureurl_product_productsize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pictureUrl',
            field=models.CharField(default='/image1.png', max_length=256),
        ),
    ]
